### Handling Imbalaced Dataset
1. Up Sampling
2. Down Sampling

In [6]:
import numpy as np
import pandas as pd

## Set the random seed for reproducibility
np.random.seed(123)  ## Seed makes random results reproducible.##123 can be replaced with another number, such as 42, 10, etc.

##Create a dataframe with two classes

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [7]:
n_class_0,n_class_1

(900, 100)

In [8]:
### Create my dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0     
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1 
})

In [9]:
df= pd.concat([class_0,class_1]).reset_index(drop=True)

In [10]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [11]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [12]:
## upsampling 
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [13]:
from sklearn.utils import resample
df_minority_upsample = resample(df_minority,replace=True, # Sample with replacement 
        n_samples = len(df_majority),
        random_state = 42
        )

In [14]:
df_minority_upsample.shape

(900, 3)

In [15]:
df_minority_upsample.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [18]:
df_upsampled = pd.concat([df_majority,df_minority_upsample])

In [19]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### down sampling

In [20]:

##Create a dataframe with two classes

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0     
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1 
})

df= pd.concat([class_0,class_1]).reset_index(drop=True)

## Check the class distribution 
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [22]:
##downsampling
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [23]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority,replace=False,
        n_samples = len(df_minority),
        random_state = 42
        )

In [24]:
df_majority_downsampled.shape

(100, 3)

In [25]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [26]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64