### label Encoding
#### label encoding and ordinal encoding are two techniques usedd to encode categorical data as numerical data 

#### Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. for exxample, if we have a categorical variable "color" with three possible values (red,green,blue), we can represent it using label encoding as follows:

#### 1.Red:1
#### 2.Green:2
#### 3.BLue:3

In [5]:
import pandas as pd
from  sklearn.preprocessing import OneHotEncoder

In [6]:
df = pd.DataFrame({
    'color' : ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [7]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [8]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [14]:
lbl_encoder.fit_transform(df['color'])

array([2, 0, 1, 1, 2, 0])

In [16]:
lbl_encoder.transform(['green'])

array([1])

#### Ordinal Encoding
##### Ordinal Encoding is used to convert categorical data that has a meaningful order/ranking into numbers.

##### Example 
###### 1. Small  → 0
###### 2.Medium → 1
###### 3.Large  → 2

In [17]:
### Ordinal encoding

from sklearn.preprocessing import OrdinalEncoder

In [18]:
### Create a sample dataframe with an ordinal variable 

df = pd.DataFrame({
    'size': ['small','medium','large','medium','small','large']
})

In [19]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [20]:
## create an instance of ordinal encoder and then fit_tranforms

encoder = OrdinalEncoder(categories = [['small','medium','large']])

In [21]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [22]:
encoder.transform([['small']])

c:\Users\HP\OneDrive\Attachments\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])